# Generated by Django 2.2.1 on 2020-05-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'POST', 'verbose_name_plural': 'POSTS'},
        ),
    ]
